=== bnotezz/finzvit/opis_strukturi-poliv-do-form-fin_zvitnosti/Ф.3 S0100311/S0100311.XSD
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Ф3. Звiт про рух грошових коштiв (за прямим методом)</xs:documentation>
  </xs:annotation>

<xs:include schemaLocation="common_types.xsd" />

  <xs:element name="DECLAR" type="DeclarContent"/>
  <xs:complexType name="DeclarContent">
    <xs:sequence>
      <xs:element name="DECLARHEAD" type="DHead"/>
      <xs:element name="DECLARBODY" type="DBody"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DHead">
    <xs:sequence>
      <xs:element name="TIN" type="DGLong" minOccurs="1" maxOccurs="1"/>
      <xs:element name="C_DOC" type="xs:string" minOccurs="1" maxOccurs="1" fixed="S01"/>
      <xs:element name="C_DOC_SUB" type="xs:string" minOccurs="1" maxOccurs="1" fixed="003"/>
      <xs:element name="C_DOC_VER" type="xs:string" minOccurs="1" maxOccurs="1" fixed="11"/>
      <xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
      <xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
      <xs:element name="C_REG" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="C_RAJ" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PERIOD_MONTH" type="DGMonth" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PERIOD_TYPE" type="DGPType" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PERIOD_YEAR" type="DGYear" minOccurs="1" maxOccurs="1"/>
      <xs:element name="D_FILL" type="DGDate" minOccurs="1" maxOccurs="1"/>
      <xs:element name="SOFTWARE" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DBody">
    <xs:sequence>
      <!-- Main -->
      <xs:element name="FIRM_BUH" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="FIRM_EDRPOU" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="FIRM_NAME" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="FIRM_RUK" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="REP_PERNM" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="LASTDAY" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="OBL" type="STATOBL"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="RAY" type="STATRAY"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3000_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3000_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3005_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3005_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3010_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3010_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3006_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3006_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3095_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3095_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3100_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3100_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3105_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3105_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3110_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3110_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3115_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3115_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3190_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3190_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3195_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3195_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3200_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3200_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3205_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3205_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3215_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3215_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3220_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3220_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3225_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3225_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3250_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3250_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3255_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3255_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3260_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3260_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3270_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3270_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3290_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3290_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3295_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3295_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3300_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3300_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3305_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3305_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3340_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3340_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3345_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3345_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3350_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3350_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3355_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3355_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3390_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3390_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3395_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3395_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3400_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3400_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3405_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3405_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3410_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3410_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3415_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3415_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3011_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3011_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3015_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3015_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3020_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3020_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3025_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3025_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3035_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3035_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3040_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3040_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3045_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3045_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3050_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3050_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3055_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3055_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3116_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3116_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3117_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3117_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3118_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3118_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3135_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3135_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3140_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3140_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3145_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3145_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3150_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3150_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3155_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3155_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3230_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3230_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3235_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3235_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3275_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3275_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3280_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3280_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3310_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3310_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3360_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3360_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3365_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3365_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3370_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3370_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3375_3" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="A3375_4" type="xs:decimal"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="N1" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="N2" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
      <xs:element name="KATOTTG" type="xs:string"  nillable="true" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
<!-- 26.02.2024 12:56:56 -->

=== bnotezz/finzvit/sample/32673400_460140032673400S010031110000006122025.XML_2026-06-05 16:47:45.xml
<?xml version="1.0" encoding="UTF-8"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="S0100311.xsd">
  <DECLARHEAD>
    <TIN>32673400</TIN>
    <C_DOC>S01</C_DOC>
    <C_DOC_SUB>003</C_DOC_SUB>
    <C_DOC_VER>11</C_DOC_VER>
    <C_DOC_TYPE>0</C_DOC_TYPE>
    <C_DOC_CNT>00006</C_DOC_CNT>
    <C_REG>46</C_REG>
    <C_RAJ>014</C_RAJ>
    <PERIOD_MONTH>12</PERIOD_MONTH>
    <PERIOD_TYPE>5</PERIOD_TYPE>
    <PERIOD_YEAR>2025</PERIOD_YEAR>
    <D_FILL>05062026</D_FILL>
    <SOFTWARE>Арт-Звіт Pro - версія 5.8.8</SOFTWARE>
  </DECLARHEAD>
  <DECLARBODY>
    <FIRM_BUH>Сеймівська Марія Ігорівна</FIRM_BUH>
    <FIRM_EDRPOU>32673400</FIRM_EDRPOU>
    <FIRM_NAME>ТзОВ "Кормотех"</FIRM_NAME>
    <FIRM_RUK>СТЕФАНИШИН МАРІЯ МИХАЙЛІВНА</FIRM_RUK>
    <REP_PERNM>Рік 2025</REP_PERNM>
    <LASTDAY>1</LASTDAY>
    <OBL>46</OBL>
    <RAY>014</RAY>
    <A3000_3>7206237</A3000_3>
    <A3000_4>6085832</A3000_4>
    <A3005_3>380</A3005_3>
    <A3005_4>662</A3005_4>
    <A3010_3>815</A3010_3>
    <A3010_4>3944</A3010_4>
    <A3006_3>63</A3006_3>
    <A3006_4>110</A3006_4>
    <A3095_3>10770</A3095_3>
    <A3095_4>7497</A3095_4>
    <A3100_3>5766351</A3100_3>
    <A3100_4>4700666</A3100_4>
    <A3105_3>479443</A3105_3>
    <A3105_4>394248</A3105_4>
    <A3110_3>109284</A3110_3>
    <A3110_4>96601</A3110_4>
    <A3115_3>598609</A3115_3>
    <A3115_4>544048</A3115_4>
    <A3190_3>70700</A3190_3>
    <A3190_4>45744</A3190_4>
    <A3195_3>164648</A3195_3>
    <A3195_4>308387</A3195_4>
    <A3200_3 xsi:nil="true"></A3200_3>
    <A3200_4 xsi:nil="true"></A3200_4>
    <A3205_3>3614</A3205_3>
    <A3205_4>3637</A3205_4>
    <A3215_3 xsi:nil="true"></A3215_3>
    <A3215_4 xsi:nil="true"></A3215_4>
    <A3220_3 xsi:nil="true"></A3220_3>
    <A3220_4 xsi:nil="true"></A3220_4>
    <A3225_3 xsi:nil="true"></A3225_3>
    <A3225_4 xsi:nil="true"></A3225_4>
    <A3250_3 xsi:nil="true"></A3250_3>
    <A3250_4>8000</A3250_4>
    <A3255_3 xsi:nil="true"></A3255_3>
    <A3255_4 xsi:nil="true"></A3255_4>
    <A3260_3>128950</A3260_3>
    <A3260_4>53568</A3260_4>
    <A3270_3 xsi:nil="true"></A3270_3>
    <A3270_4 xsi:nil="true"></A3270_4>
    <A3290_3 xsi:nil="true"></A3290_3>
    <A3290_4 xsi:nil="true"></A3290_4>
    <A3295_3>-125336</A3295_3>
    <A3295_4>-41931</A3295_4>
    <A3300_3 xsi:nil="true"></A3300_3>
    <A3300_4 xsi:nil="true"></A3300_4>
    <A3305_3>416300</A3305_3>
    <A3305_4>171751</A3305_4>
    <A3340_3>112</A3340_3>
    <A3340_4>39514</A3340_4>
    <A3345_3 xsi:nil="true"></A3345_3>
    <A3345_4 xsi:nil="true"></A3345_4>
    <A3350_3>312837</A3350_3>
    <A3350_4>101774</A3350_4>
    <A3355_3>99287</A3355_3>
    <A3355_4>189804</A3355_4>
    <A3390_3>8828</A3390_3>
    <A3390_4>40352</A3390_4>
    <A3395_3>-103030</A3395_3>
    <A3395_4>-213591</A3395_4>
    <A3400_3>-63718</A3400_3>
    <A3400_4>52865</A3400_4>
    <A3405_3>66978</A3405_3>
    <A3405_4>14250</A3405_4>
    <A3410_3>-6</A3410_3>
    <A3410_4>-137</A3410_4>
    <A3415_3>3254</A3415_3>
    <A3415_4>66978</A3415_4>
    <A3011_3>499</A3011_3>
    <A3011_4>83</A3011_4>
    <A3015_3 xsi:nil="true"></A3015_3>
    <A3015_4 xsi:nil="true"></A3015_4>
    <A3020_3>10016</A3020_3>
    <A3020_4>7414</A3020_4>
    <A3025_3>719</A3025_3>
    <A3025_4>320</A3025_4>
    <A3035_3>43</A3035_3>
    <A3035_4>4086</A3035_4>
    <A3040_3>18</A3040_3>
    <A3040_4>292</A3040_4>
    <A3045_3 xsi:nil="true"></A3045_3>
    <A3045_4 xsi:nil="true"></A3045_4>
    <A3050_3 xsi:nil="true"></A3050_3>
    <A3050_4 xsi:nil="true"></A3050_4>
    <A3055_3 xsi:nil="true"></A3055_3>
    <A3055_4 xsi:nil="true"></A3055_4>
    <A3116_3>16099</A3116_3>
    <A3116_4>65897</A3116_4>
    <A3117_3>407288</A3117_3>
    <A3117_4>364127</A3117_4>
    <A3118_3>175222</A3118_3>
    <A3118_4>114024</A3118_4>
    <A3135_3 xsi:nil="true"></A3135_3>
    <A3135_4 xsi:nil="true"></A3135_4>
    <A3140_3 xsi:nil="true"></A3140_3>
    <A3140_4>2284</A3140_4>
    <A3145_3>39963</A3145_3>
    <A3145_4>18069</A3145_4>
    <A3150_3 xsi:nil="true"></A3150_3>
    <A3150_4 xsi:nil="true"></A3150_4>
    <A3155_3 xsi:nil="true"></A3155_3>
    <A3155_4 xsi:nil="true"></A3155_4>
    <A3230_3 xsi:nil="true"></A3230_3>
    <A3230_4 xsi:nil="true"></A3230_4>
    <A3235_3 xsi:nil="true"></A3235_3>
    <A3235_4 xsi:nil="true"></A3235_4>
    <A3275_3 xsi:nil="true"></A3275_3>
    <A3275_4 xsi:nil="true"></A3275_4>
    <A3280_3 xsi:nil="true"></A3280_3>
    <A3280_4 xsi:nil="true"></A3280_4>
    <A3310_3 xsi:nil="true"></A3310_3>
    <A3310_4 xsi:nil="true"></A3310_4>
    <A3360_3>55851</A3360_3>
    <A3360_4>49391</A3360_4>
    <A3365_3>42639</A3365_3>
    <A3365_4>43535</A3365_4>
    <A3370_3 xsi:nil="true"></A3370_3>
    <A3370_4 xsi:nil="true"></A3370_4>
    <A3375_3 xsi:nil="true"></A3375_3>
    <A3375_4 xsi:nil="true"></A3375_4>
    <N1>2026</N1>
    <N2>1</N2>
    <KATOTTG>UA46140050150014119</KATOTTG>
  </DECLARBODY>
</DECLAR>
